### ISSUE TITLE
Is it safe to run application built on Debian on Aline?

### ISSUE THREAD

**Issue by baurzhan** [Spikhalskiy/zerotier-containerized#1]
When building sources on Debian application linked on libc libraries but Alpine based on muslc libraries. Should it be an issue?

**Comment by Spikhalskiy** [comment]
@baurzhan That's the problem I solve by [installing libc6-compat](https://github.com/Spikhalskiy/zerotier-containerized/blob/master/Dockerfile#L19) - to make Zerotier linked for glibc work on musl. You can find a docker with Debian as a base image in the Zerotier upstream: https://github.com/zerotier/ZeroTierOne/blob/master/ext/installfiles/linux/zerotier-containerized/Dockerfile
it's just a much heavier resulting image.
