### ISSUE TITLE
zerotier-one: /usr/lib/libstdc++.so.6: no version information available (required by zerotier-one)

### ISSUE THREAD

**Issue by ChasLui** [Spikhalskiy/zerotier-containerized#7]
zerotier-one: /usr/lib/libstdc++.so.6: no version information available (required by zerotier-one)

**Comment by Spikhalskiy** [comment]
Not a bug and doesn't interfere with any functionality, I'm not going to invest time into investigation. 
Contributions are welcomed if you want to get rid of the message.
